services:
  - type: web
    name: resolve-indexer
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: STELLAR_NETWORK
        value: testnet
      - key: SOROBAN_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: RESOLVE_CONTRACT_ID
        value: CD3YJNAYKVKT72DYPVS644OPNVNW6673TUIQWGXXA4VQD7536ARWB6MZ
      - key: NETWORK_PASSPHRASE
        value: Test SDF Network ; September 2015
      - key: DATABASE_PATH
        value: /data/indexer.sqlite
      - key: CORS_ORIGINS
        value: https://resolveit-app.vercel.app,http://localhost:3000
      - key: BACKFILL_MARKET_META
        value: "true"
    disk:
      name: resolve-indexer-data
      mountPath: /data
      sizeGB: 1
